/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidades.Sale;
import Services.SaleService;
import Util.Utils;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Payment_Money extends javax.swing.JDialog {

    private New_Sale saleWindow;
    private Sale sale;

    /**
     * Creates new form Payment_Money
     */
    public Payment_Money(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        saleWindow = ((Payment) parent).getSaleWindow();
        sale = saleWindow.getSale();
        txtAmountReceived.requestFocusInWindow();

        txtSalePrice.setText(String.format("%.2f", sale.getTotal()));
        btConfirm.setEnabled(false);
        btEdit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAmountReceived = new javax.swing.JFormattedTextField();
        txtChange = new javax.swing.JTextField();
        txtSalePrice = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btCancel = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        btConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 176, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pagamento em Dinheiro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 440, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Valor recebido :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Valor da venda :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Troco :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 30));

        txtAmountReceived.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtAmountReceived.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmountReceived.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAmountReceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmountReceivedKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountReceivedKeyTyped(evt);
            }
        });
        jPanel1.add(txtAmountReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 60, 30));

        txtChange.setEditable(false);
        txtChange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeActionPerformed(evt);
            }
        });
        jPanel1.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, 30));

        txtSalePrice.setEditable(false);
        txtSalePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalePrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSalePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btCancel.setBackground(new java.awt.Color(192, 0, 0));
        btCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("Cancelar");
        btCancel.setBorderPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, 40));

        btEdit.setBackground(new java.awt.Color(255, 255, 51));
        btEdit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_19px.png"))); // NOI18N
        btEdit.setBorderPainted(false);
        btEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditMouseClicked(evt);
            }
        });
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        btEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btEditKeyPressed(evt);
            }
        });
        jPanel1.add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 30));

        btOk.setBackground(new java.awt.Color(0, 176, 80));
        btOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btOk.setForeground(new java.awt.Color(255, 255, 255));
        btOk.setText("OK");
        btOk.setBorderPainted(false);
        btOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btOkMouseClicked(evt);
            }
        });
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        btOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btOkKeyPressed(evt);
            }
        });
        jPanel1.add(btOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 50, 30));

        btConfirm.setBackground(new java.awt.Color(0, 176, 80));
        btConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btConfirm.setText("Finalizar Venda");
        btConfirm.setBorderPainted(false);
        btConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConfirmMouseClicked(evt);
            }
        });
        btConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmActionPerformed(evt);
            }
        });
        btConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btConfirmKeyPressed(evt);
            }
        });
        jPanel1.add(btConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_Pagamento_Dinheiro.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
        // Verifique se o campo de valor recebido está preenchido e válido
        Double amountReceived = Utils.tryParseToDouble(txtAmountReceived.getText().replace(',', '.'));

        if (amountReceived == null || amountReceived <= 0) {
            JOptionPane.showMessageDialog(this, "Digite um valor válido para poder finalizar", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe a execução caso a condição seja verdadeira
        }

        Double change = amountReceived - sale.getTotal();

        if (change < 0) {
            JOptionPane.showMessageDialog(this, "O valor recebido não pode ser menor que o valor cobrado", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe a execução caso a condição seja verdadeira
        }

        // Se todas as verificações passarem, finalize a venda
        saleWindow.finishSale();
        this.dispose();
    }//GEN-LAST:event_btConfirmActionPerformed

    private void txtAmountReceivedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountReceivedKeyPressed

    }//GEN-LAST:event_txtAmountReceivedKeyPressed

    private void btConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btConfirmMouseClicked

    private void btConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConfirmKeyPressed

    }//GEN-LAST:event_btConfirmKeyPressed

    private void txtAmountReceivedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountReceivedKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountReceivedKeyTyped

    private void btOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOkMouseClicked

        // Tente converter o valor inserido para Double
        Double amountReceived = Utils.tryParseToDouble(txtAmountReceived.getText().replace(',', '.'));

        if (amountReceived == null || amountReceived <= 0) {
            JOptionPane.showMessageDialog(this, "Digite um valor válido para poder finalizar", "Erro", JOptionPane.ERROR_MESSAGE);
            txtAmountReceived.setText(""); // Limpa o campo para evitar confusão
            btConfirm.setEnabled(false);
            return;
        }

        Double change = amountReceived - sale.getTotal();

        if (change < 0) {
            JOptionPane.showMessageDialog(this, "O valor recebido não pode ser menor que o valor cobrado", "Erro", JOptionPane.ERROR_MESSAGE);
            txtAmountReceived.setText(""); // Limpa o campo para evitar confusão
            btConfirm.setEnabled(false);
            return;
        }

        txtChange.setText(String.format("%.2f", change));
        txtAmountReceived.setEnabled(false);
        btConfirm.setEnabled(true); // Habilita o botão confirmar
        btEdit.setEnabled(true); // Habilita o botão confirmar
        
    }//GEN-LAST:event_btOkMouseClicked

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOkActionPerformed

    private void btOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btOkKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOkKeyPressed

    private void btEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditMouseClicked

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        txtAmountReceived.setText(""); // Limpa o campo para evitar confusão
        txtAmountReceived.setEnabled(true);
        txtChange.setText(""); // Limpa o campo para evitar confusão
        btConfirm.setEnabled(false);
    }//GEN-LAST:event_btEditActionPerformed

    private void btEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEditKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditKeyPressed

    private void txtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btConfirm;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField txtAmountReceived;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtSalePrice;
    // End of variables declaration//GEN-END:variables
}
